---
- name: Enable COPR repository
  yum_repository:
    name: copr-alacritty
    description: Copr repo for alacritty owned by pschyska
    enabled: yes
    baseurl: https://copr-be.cloud.fedoraproject.org/results/pschyska/alacritty/fedora-$releasever-$basearch/
    gpgkey: https://copr-be.cloud.fedoraproject.org/results/pschyska/alacritty/pubkey.gpg
    gpgcheck: yes
    skip_if_unavailable: yes

- name: Install Alacritty
  dnf:
    name: alacritty
    state: present
